// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-56XpMomit1twAEGeldMfxiRomSpk_Hw',
    appId: '1:813340157825:web:f781c29c901f81c77fea80',
    messagingSenderId: '813340157825',
    projectId: 'buysell-1b12a',
    authDomain: 'buysell-1b12a.firebaseapp.com',
    storageBucket: 'buysell-1b12a.appspot.com',
    measurementId: 'G-81K7BH6T23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdG5lonxAQXs9mwwF9BgyFXRLqsJqmmns',
    appId: '1:813340157825:android:f240c41f1c8ea7be7fea80',
    messagingSenderId: '813340157825',
    projectId: 'buysell-1b12a',
    storageBucket: 'buysell-1b12a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYgiNJFgqBQxz9Ttkfg60A-Xxwa8FbOQw',
    appId: '1:813340157825:ios:808b7244776af4df7fea80',
    messagingSenderId: '813340157825',
    projectId: 'buysell-1b12a',
    storageBucket: 'buysell-1b12a.appspot.com',
    androidClientId: '813340157825-48kae6738nsc3llj0eabn2cfej6qu079.apps.googleusercontent.com',
    iosClientId: '813340157825-55peqje51r1s8evblickslb0mq4htjql.apps.googleusercontent.com',
    iosBundleId: 'com.example.buysell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYgiNJFgqBQxz9Ttkfg60A-Xxwa8FbOQw',
    appId: '1:813340157825:ios:bf9f48cb0ca7a2757fea80',
    messagingSenderId: '813340157825',
    projectId: 'buysell-1b12a',
    storageBucket: 'buysell-1b12a.appspot.com',
    androidClientId: '813340157825-48kae6738nsc3llj0eabn2cfej6qu079.apps.googleusercontent.com',
    iosClientId: '813340157825-vqklrb0hmp66hc8mvqrudejk90s2627v.apps.googleusercontent.com',
    iosBundleId: 'com.example.buysell.RunnerTests',
  );
}
